#!/usr/bin/env python3
"""
ST File Converter for ST dialect to RuSTy Conversion

This script reads a transformation list (JSON) generated by st_analyzer.py
and applies the transformations to the ST files.

Usage:
    python st_converter.py <transformations.json> --output-dir <derived-dir> [--dry-run]
"""

import os
import re
import json
import shutil
import argparse
from pathlib import Path
from typing import List, Dict, Any
from collections import defaultdict

from dialect_rules import RULES


def load_transformations(json_path: str) -> Dict[str, Any]:
    """Load transformation list from JSON file."""
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def materialize_derived_copy(source: Path, output_dir: Path) -> dict[Path, Path]:
    """Copy ST input to a fresh derived directory and return source mappings."""
    source = source.resolve()
    output_dir = output_dir.resolve()
    if output_dir == source or source in output_dir.parents:
        raise SystemExit("output directory must not be the source or lie inside it")
    if output_dir.exists() and any(output_dir.iterdir()):
        raise SystemExit(f"output directory is not empty: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)

    mapping: dict[Path, Path] = {}
    if source.is_file():
        destination = output_dir / source.name
        shutil.copy2(source, destination)
        mapping[source] = destination
        return mapping

    for item in sorted(source.rglob("*.st")):
        destination = output_dir / item.relative_to(source)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, destination)
        mapping[item.resolve()] = destination
    return mapping


def apply_transformations_to_file(
    file_path: str,
    transformations: List[Dict[str, Any]],
    dry_run: bool = False
) -> int:
    """Apply transformations to a single file."""

    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
    except Exception as e:
        print(f"  ❌ Error reading file: {e}")
        return 0

    # Separate transformations by type
    append_transforms = [t for t in transformations if t.get('transform_type') == 'append']
    pou_convert_transforms = [t for t in transformations if t.get('transform_type') == 'pou_convert']
    replace_transforms = [t for t in transformations if t.get('transform_type', 'replace') == 'replace']

    changes_made = 0

    # Process replace transformations
    # Group by line number (descending to avoid offset issues)
    by_line = defaultdict(list)
    for t in replace_transforms:
        by_line[t['line_number']].append(t)

    # Process lines in reverse order to maintain line numbers
    for line_num in sorted(by_line.keys(), reverse=True):
        line_idx = line_num - 1
        if line_idx < 0 or line_idx >= len(lines):
            print(f"  ⚠️ Line {line_num} out of range")
            continue

        original_line = lines[line_idx]
        modified_line = original_line

        positioned = sorted(
            by_line[line_num], key=lambda item: item.get('column_start', 0), reverse=True
        )
        for t in positioned:
            start = t.get('column_start', 0)
            end = t.get('column_end', 0)
            if end > start and original_line[start:end] == t['original_text']:
                modified_line = modified_line[:start] + t['replacement_text'] + modified_line[end:]
                continue
            # Backward-compatible manifests lack columns. Replace one reviewed occurrence.
            pattern = re.compile(re.escape(t['original_text']), re.IGNORECASE)
            modified_line = pattern.sub(t['replacement_text'], modified_line, count=1)

        if modified_line != original_line:
            lines[line_idx] = modified_line
            changes_made += 1

            if dry_run:
                print(f"  Line {line_num}:")
                print(f"    - {original_line.strip()}")
                print(f"    + {modified_line.strip()}")

    # Process POU conversion transformations (Rule 12: METHOD → FUNCTION)
    for t in pou_convert_transforms:
        line_num = t['line_number']
        line_idx = line_num - 1
        if line_idx < 0 or line_idx >= len(lines):
            print(f"  ⚠️ Line {line_num} out of range")
            continue

        original_text = t['original_text']
        replacement_text = t['replacement_text']
        original_line = lines[line_idx]

        start = t.get('column_start', 0)
        end = t.get('column_end', 0)
        if end > start and original_line[start:end].upper() == original_text.upper():
            modified_line = original_line[:start] + replacement_text + original_line[end:]
        else:
            pattern = re.compile(rf'\b{re.escape(original_text)}\b', re.IGNORECASE)
            modified_line = pattern.sub(replacement_text, original_line, count=1)

        if modified_line != original_line:
            lines[line_idx] = modified_line
            changes_made += 1

            if dry_run:
                print(f"  Line {line_num} ({t['rule_name']}):")
                print(f"    - {original_line.strip()}")
                print(f"    + {modified_line.strip()}")

    # Process append transformations (add missing END_* keywords)
    for t in append_transforms:
        keyword = t['replacement_text']
        # Ensure file ends with newline before adding END_*
        if lines and not lines[-1].endswith('\n'):
            lines[-1] += '\n'
        lines.append(keyword + '\n')
        changes_made += 1

        if dry_run:
            print(f"  Append at EOF: {keyword}")

    if not dry_run and changes_made > 0:
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.writelines(lines)
        except Exception as e:
            print(f"  ❌ Error writing file: {e}")
            return 0

    return changes_made


def main():
    parser = argparse.ArgumentParser(
        description='Apply ST file transformations from JSON list'
    )
    parser.add_argument(
        'json_file',
        help='JSON file containing transformation list (from st_analyzer.py)'
    )
    parser.add_argument(
        '--output-dir',
        required=True,
        help='Fresh artifacts/cache or user-selected directory for the compatible copy'
    )
    parser.add_argument(
        '--dry-run', '-n',
        action='store_true',
        help='Show what would be changed without modifying files'
    )
    parser.add_argument(
        '--allow-reviewed-rule',
        action='append',
        type=int,
        default=[],
        help='rule ID with library-specific equivalence evidence; repeat as needed'
    )
    args = parser.parse_args()

    # Load transformation list
    if not os.path.isfile(args.json_file):
        print(f"Error: {args.json_file} not found")
        return 1

    data = load_transformations(args.json_file)
    transformations = data.get('transformations', [])
    unsupported = [t for t in transformations if t.get('safety') == 'unsupported']
    if unsupported:
        names = ', '.join(sorted({t['rule_name'] for t in unsupported}))
        raise SystemExit(f"unsupported constructs block conversion: {names}")
    unreviewed = [
        t for t in transformations
        if t.get('safety') == 'review_required' and t['rule_id'] not in args.allow_reviewed_rule
    ]
    if unreviewed:
        rule_ids = ', '.join(str(value) for value in sorted({t['rule_id'] for t in unreviewed}))
        raise SystemExit(
            f"rules require semantic evidence before conversion: {rule_ids}; "
            "pass --allow-reviewed-rule only after recording that evidence"
        )

    source = Path(data.get('source_directory', '')).resolve()
    if not source.exists():
        print(f"Error: analyzed source does not exist: {source}")
        return 1
    output_dir = Path(args.output_dir).resolve()
    source_mapping = materialize_derived_copy(source, output_dir) if not args.dry_run else {}
    if not transformations:
        print("No transformations found; materialized an unchanged derived copy.")

    # Group by derived file. The original analyzed paths remain in the audit JSON.
    by_file = defaultdict(list)
    for t in transformations:
        original = Path(t['file_path']).resolve()
        if args.dry_run:
            by_file[str(original)].append(t)
        elif original in source_mapping:
            by_file[str(source_mapping[original])].append(t)
        else:
            raise SystemExit(f"transformation path is outside analyzed source: {original}")

    print("=" * 60)
    print("ST to RuSTy Converter")
    print("=" * 60)
    print(f"\nSource: {data.get('source_directory', 'Unknown')}")
    print(f"Files to modify: {len(by_file)}")
    print(f"Total transformations: {len(transformations)}")

    if args.dry_run:
        print("\n🔍 DRY RUN MODE - No files will be modified\n")

    # Apply transformations
    print("\n" + "-" * 60)
    total_changes = 0
    files_modified = 0

    for file_path, file_transformations in sorted(by_file.items()):
        print(f"\n📄 {Path(file_path).name}")
        print(f"   Path: {file_path}")
        print(f"   Transformations: {len(file_transformations)}")

        if not os.path.isfile(file_path):
            print(f"   ❌ File not found!")
            continue

        # Apply
        changes = apply_transformations_to_file(
            file_path,
            file_transformations,
            dry_run=args.dry_run
        )

        if changes > 0:
            total_changes += changes
            files_modified += 1
            status = "would be modified" if args.dry_run else "modified"
            print(f"   ✅ {changes} line(s) {status}")
        else:
            print(f"   ⏭️ No changes needed")

    # Summary
    print("\n" + "=" * 60)
    print("## Summary\n")

    if args.dry_run:
        print(f"- Files that would be modified: {files_modified}")
        print(f"- Lines that would change: {total_changes}")
        print("\nRun without --dry-run to apply changes.")
    else:
        print(f"- Files modified: {files_modified}")
        print(f"- Lines changed: {total_changes}")
        print(f"- Original preserved: {source}")
        print(f"- Derived copy: {output_dir}")
        print("\n✅ Conversion complete!")

    return 0


if __name__ == '__main__':
    exit(main())
